- name: copy docker compose
  copy: 
    src: ./docker-compose.yml
    dest: /home/ahmed/docker-compose.yml

- name: docker login
  docker_login:
    registry_url: https://index.docker.io/v1/
    username: doc299
    password: "{{docker_password}}"

- name: start container from compose
  community.docker.docker_compose:
    project_src: /home/ahmed
    state: present
